// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleNote.Api.Data;

namespace SimpleNote.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211213074336_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimpleNote.Api.Data.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Lorem ipsum dolor sit amet.",
                            Time = new DateTime(2021, 12, 13, 10, 43, 35, 621, DateTimeKind.Local).AddTicks(4431),
                            Title = "Sample Note 1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Lorem ipsum dolor sit amet.",
                            Time = new DateTime(2021, 12, 13, 10, 43, 35, 623, DateTimeKind.Local).AddTicks(1078),
                            Title = "Sample Note 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
